### ISSUE TITLE
There  are some questions about loading data.

### ISSUE THREAD

**Issue by DavidZhang88** [QiangAIResearcher/sahp_repo#1]
Hello, when I was trying to running you model, I encountered two problems. 

First, when I was loading the retweet data:
`        train_path = 'data/' + args.task + '/train_manifold_format.pkl'
        dev_path = 'data/' + args.task + '/dev_manifold_format.pkl'
        test_path = 'data/' + args.task + '/test_manifold_format.pkl'

        chosen_file = args.task

        with open(train_path, 'rb') as f:
            train_hawkes_data = pickle.load(f)
        with open(dev_path, 'rb') as f:
            dev_hawkes_data = pickle.load(f)
        with open(test_path, 'rb') as f:
            test_hawkes_data = pickle.load(f)`

It comes out that: `UnicodeDecodeError
'ascii' codec can't decode byte 0x80 in position 2: ordinal not in range(128)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/ZhangLuNing/sahp_repo-master/main_func.py", line 145, in <module>
    train_hawkes_data = pickle.load(f)`

Then I add the encoding setting of pickle.load:

`       with open(train_path, 'rb') as f:
            train_hawkes_data = pickle.load(f,encoding='latin1')
        with open(dev_path, 'rb') as f:
            dev_hawkes_data = pickle.load(f,encoding='latin1')
        with open(test_path, 'rb') as f:
            test_hawkes_data = pickle.load(f,encoding='latin1')`

It shows that `UnpicklingError: pickle data was truncated` , I don't know how to fix it, could you offer me some help?

**Comment by DavidZhang88** [comment]
I didn't see the 'convert_realdata_syntheform.py' sorry for my carelessness. Your research is very meaningful and I hope to have more opportunities to communicate with you and learn from you in the future.

**Comment by QiangAIResearcher** [comment]
> Hello, when I was trying to running you model, I encountered two problems.
> 
> First, when I was loading the retweet data:
> ` train_path = 'data/' + args.task + '/train_manifold_format.pkl'
> dev_path = 'data/' + args.task + '/dev_manifold_format.pkl'
> test_path = 'data/' + args.task + '/test_manifold_format.pkl'
> 
> ```
>     chosen_file = args.task
> 
>     with open(train_path, 'rb') as f:
>         train_hawkes_data = pickle.load(f)
>     with open(dev_path, 'rb') as f:
>         dev_hawkes_data = pickle.load(f)
>     with open(test_path, 'rb') as f:
>         test_hawkes_data = pickle.load(f)`
> ```
> 
> It comes out that: `UnicodeDecodeError 'ascii' codec can't decode byte 0x80 in position 2: ordinal not in range(128) File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/ZhangLuNing/sahp_repo-master/main_func.py", line 145, in <module> train_hawkes_data = pickle.load(f)`
> 
> Then I add the encoding setting of pickle.load:
> 
> ` with open(train_path, 'rb') as f: train_hawkes_data = pickle.load(f,encoding='latin1') with open(dev_path, 'rb') as f: dev_hawkes_data = pickle.load(f,encoding='latin1') with open(test_path, 'rb') as f: test_hawkes_data = pickle.load(f,encoding='latin1')`
> 
> It shows that `UnpicklingError: pickle data was truncated` , I don't know how to fix it, could you offer me some help?

have you solved this problem?

**Comment by QiangAIResearcher** [comment]
> I didn't see the 'convert_realdata_syntheform.py' sorry for my carelessness. Your research is very meaningful and I hope to have more opportunities to communicate with you and learn from you in the future.

Great! I'll upload the synthetic dataset later.

**Comment by DavidZhang88** [comment]
> > I didn't see the 'convert_realdata_syntheform.py' sorry for my carelessness. Your research is very meaningful and I hope to have more opportunities to communicate with you and learn from you in the future.
> 
> Great! I'll upload the synthetic dataset later.

The problem is solved， because I try to  import the original data into the model directly, rather than using  'convert_realdata_syntheform.py'

Thank you so much for your generous help.   
And I still have a little question to want to ask you, in 'convert_realdata_syntheform.py' you also used 'encoding = 'lantin1' ', while the source code of Mei of the Nerual Hawkes only used 'pickle.load'.  Is it because his code is based on theano and python2, and the current code is based on python3?
