### ISSUE TITLE
KeyError: 'lengths' when running process_loaded_sequences

### ISSUE THREAD

**Issue by slowlyswimming** [QiangAIResearcher/sahp_repo#2]
I tried to load the mimic and retweet dataset in main_func.py after downloading to the local folders. But when running process_loaded_sequences, it raised the error: KeyError: 'lengths' with code line:

`seq_lengths = torch.Tensor(loaded_hawkes_data['lengths']).int()`

**Comment by QiangAIResearcher** [comment]
Hi,

Thanks for your interest in our work. It has been clearly explained in the Readme file that "To make the data format consistent, it is necessary to run the script convert_realdata_syntheform.py first. "

Hope that helps you.

**Comment by slowlyswimming** [comment]
Got it. Thanks for your information.
