### ISSUE TITLE
Error detected in SoftmaxBackward

### ISSUE THREAD

**Issue by siowan** [QiangAIResearcher/sahp_repo#4]
Hello, I tried to use the SOF dataset to run in main_func.py. But it returns the error: 

[W python_anomaly_mode.cpp:60] Warning: Error detected in SoftmaxBackward. Traceback of forward call that caused the error:
  File "main_func.py", line 206, in <module>
    model = train_eval_sahp(params)
 
Could you share some ideas to let me know how to fix it? Thank you very much!

**Comment by QiangAIResearcher** [comment]
I'm not sure why you met such a problem, but you can try to identify the line that produce bugs by 
with autograd.detect_anomaly()

Then you can print out the variable values and gradients of the line at question.

**Comment by siowan** [comment]
Thank you for your response, the problem is solved when I try to decrease the default batch size.
